// Code generated by protoc-gen-rainhari. DO NOT EDIT.

package example

import (
	context "context"
	client "github.com/agus7fauzi/rainhari/core/client"
	server "github.com/agus7fauzi/rainhari/core/server"
)

type greeterservice struct {
	c    client.Client
	name string
}

func NewGreeterService(name string, c client.Client) GreeterService {
	return &greeterservice{
		c:    c,
		name: name,
	}
}
