// Code generated by protoc-gen-rainhari. DO NOT EDIT.

package example

import (
	context "context"
	client "github.com/agus7fauzi/rainhari/core/client"
)

type GreeterService interface {
	Hello(ctx context.Context, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *Request, opts ...client.CallOption) (example_StreamService, error)
}

type greeterservice struct {
	c    client.Client
	name string
}

func NewGreeterService(name string, c client.Client) GreeterService {
	return &greeterservice{
		c:    c,
		name: name,
	}
}
