/*
Copyright 2022 Agus Imam Fauzi <agus7fauzi@gmail.com>

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package plugin

import (
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// GenerateFile generates *.rainhari.pb.go files containing gRPC service definitions.
func GenerateFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + ".rainhari.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.QualifiedGoIdent(protogen.GoIdent{
		GoName:       "context",
		GoImportPath: "context",
	})
	g.QualifiedGoIdent(protogen.GoIdent{
		GoName:       "server",
		GoImportPath: "github.com/agus7fauzi/rainhari/core/server",
	})
	g.QualifiedGoIdent(protogen.GoIdent{
		GoName:       "client",
		GoImportPath: "github.com/agus7fauzi/rainhari/core/client",
	})

	g.P("// Code generated by protoc-gen-rainhari. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	// Iterate through all the `service`s in the passed-in file
	for _, svc := range file.Services {

		originSvcName := svc.GoName
		// svcName := strings.ToLower(originSvcName)

		// if pkg := file.GoPackageName; pkg != "" {
		// 	svcName = string(pkg)
		// }

		cCaseSvcName := camelCase(originSvcName)
		svcAlias := cCaseSvcName + "Service"

		// Strip suffix
		if strings.HasSuffix(svcAlias, "ServiceService") {
			svcAlias = strings.TrimSuffix(svcAlias, "Service")
		}

		// Client interface
		// g.P("type ", svcAlias, " interface {")
		// for _, method := range svc.Methods {
		// }

		// Client struct
		g.P("type ", unexport(svcAlias), " struct {")
		g.P("c client.Client")
		g.P("name string")
		g.P("}")
		g.P()

		// NewClient factory
		g.P("func New", svcAlias, " (name string, c client.Client) ", svcAlias, " {")
		g.P("return &", unexport(svcAlias), "{")
		g.P("c: c,")
		g.P("name: name,")
		g.P("}")
		g.P("}")
		g.P()
	}

}

func isASCIILower(c byte) bool {
	return 'a' <= c && c <= 'z'
}

func isASCIIDigit(c byte) bool {
	return '0' <= c && c <= '9'
}

func camelCase(s string) string {
	if s == "" {
		return ""
	}
	t := make([]byte, 0, 32)
	i := 0
	if s[0] == '_' {
		// Need a capital letter; drop the '_'.
		t = append(t, 'X')
		i++
	}
	// Invariant: if the next letter is lower case, it must be converted
	// to upper case.
	// That is, we process a word at a time, where words are marked by _ or
	// upper case letter. Digits are treated as words.
	for ; i < len(s); i++ {
		c := s[i]
		if c == '_' && i+1 < len(s) && isASCIILower(s[i+1]) {
			continue // Skip the underscore in s.
		}
		if isASCIIDigit(c) {
			t = append(t, c)
			continue
		}
		// Assume we have a letter now - if not, it's a bogus identifier.
		// The next word is a sequence of characters that must start upper case.
		if isASCIILower(c) {
			c ^= ' ' // Make it a capital letter.
		}
		t = append(t, c) // Guaranteed not lower case.
		// Accept lower case sequence that follows.
		for i+1 < len(s) && isASCIILower(s[i+1]) {
			i++
			t = append(t, s[i])
		}
	}
	return string(t)
}

func unexport(s string) string {
	if len(s) == 0 {
		return ""
	}

	return strings.ToLower(s[:1] + s[1:])
}
